platform :ios, '15.0'

target 'Steez' do
  use_frameworks!

  # Networking
  pod 'Alamofire', '~> 5.6'
  
  # Image Loading
  pod 'Kingfisher', '~> 7.0'
  
  # Local Storage
  pod 'RealmSwift', '~> 10.0'
  
  # UI Components
  pod 'SnapKit', '~> 5.6'
  
  # Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end 
